[phases.setup]
nixPkgs = ["python39", "postgresql", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn smart_water_tanks.wsgi --log-file -" 